#!/bin/bash

python3 plotting_scripts/plot_actions_closedloop_bypass.py
python3 plotting_scripts/plot_actions_closedloop_encounter.py
python3 plotting_scripts/plot_actions_openloop.py
python3 plotting_scripts/plot_results_bypass.py
python3 plotting_scripts/plot_results_encounter.py
